peso= input("¿Cual es tu peso en Kg?")
estatura= input("¿Cual es tu estatura en metros?")
#imc = peso/ (estatura * estatura)
imc= round(float(peso)/float(estatura)**2,2)
print("tu indice de masa corporal es:",imc)
